### PR TITLE
fix: actually disable persistence in cascade

### LINKED ISSUE #816: withoutPersisting schedules for insert in Doctrine UnitOfWork
Hi, im unsureif it was introduced in the latest 2.3.2 version, but it seems like persistance is inconsistently handled.

Factories that have persistence disabled, are still scheduling for insert for children.

```php
 $contact = static::contactFactory()->withoutPersisting()->create([
            'tags' => static::tagFactory()::new()->many(3),
            'category' => static::categoryFactory(),
        ]);
```

This can be observed in the `\Zenstruck\Foundry\Tests\Integration\ORM\EntityRelationship\EntityFactoryRelationshipTestCase::disabling_persistence_cascades_to_children` test by checking the UnitOfWork insertions

Image

Unless withoutPersisting is not the same meaning as in doctrine, let me know if i misunderstood something here

```diff
        foreach ($contact->getTags() as $tag) {
            $this->assertNull($tag->id);
++            static::assertFalse(Configuration::instance()->persistence()->isPersisted($tag));
        }
```
i tested if i can enhance the test by a isPersisted check, but this is always returning false despite being scheduled for insert by doctrine

### PR DESCRIPTION
**Pull request by nikophil**
fixes #816

### CODE REVIEW

File: src/Persistence/IsProxy.php [hunk 1]
```diff
@@ -97,12 +97,14 @@ public function _set(string $property, mixed $value): static
         return $this;
     }
 
-    public function _real(): object
+    public function _real(bool $withAutoRefresh = true): object
```
Comment (nikophil) [inline src/Persistence/IsProxy.php:100]: this is here just to make the code less crappy in `PersistentObjectFactory`

File: src/Persistence/PersistentObjectFactory.php [hunk 2]
```diff
@@ -362,36 +361,26 @@ protected function normalizeCollection(string $field, FactoryCollection $collect
...
-        // readonly classes exist since php 8.2 and proxyHelper supports them since 8.3
-        if (80200 <= \PHP_VERSION_ID && \PHP_VERSION_ID < 80300 && $reflectionClass->isReadonly()) {
-            return $object;
-        }
-
         $configuration = Configuration::instance();
 
-        if (!$configuration->isPersistenceAvailable()) {
+        if (
+            !$this->isPersisting()
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:373]: the actual fix for #816 is this line

File: src/Persistence/PersistentObjectFactory.php [hunk 3]
```diff
@@ -362,36 +361,26 @@ protected function normalizeCollection(string $field, FactoryCollection $collect
...
-        $reflectionClass = new \ReflectionClass($object::class);
-
-        if ($reflectionClass->isFinal()) {
-            return $object;
-        }
-
-        // readonly classes exist since php 8.2 and proxyHelper supports them since 8.3
-        if (80200 <= \PHP_VERSION_ID && \PHP_VERSION_ID < 80300 && $reflectionClass->isReadonly()) {
-            return $object;
-        }
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:378]: I polished a bit this method...

since [this PR](https://github.com/zenstruck/foundry/pull/773) we don't use proxy stuff anymore to refresh the entity, so these guards are not needed anymore

**Review by kbond — APPROVED** [review]
