### PR TITLE
fix: use a "placeholder" for inversed one-to-one

### LINKED ISSUE #749: Null value for inversed one-to-one relation (v2.3.1)
I'm upgrading Foundry on my project to use the v2.

However, it seems like the inversed relation is not auto filled, resulting in a null value (and violating the constraint on insertion), which was not the case before.

I thought [this issue](https://github.com/zenstruck/foundry/issues/655) would fix ours but it's not the case (since the latest version including the fix is not working).

For the reproducer, I created an Account and AccountSetting entity.

When trying to create an Account with a specified AccountSetting, the account property of the accountSetting is not filled (it is null).
```php
\App\Factory\AccountFactory::createOne([
  'accountSetting' => \App\Factory\AccountSettingFactory::new(),
]);
```

[Link to the reproducer test](https://github.com/florian-bailly/foundry-inversed-oneone-null/blob/main/tests/SampleTest.php)

### PR DESCRIPTION
**Pull request by nikophil**
:warning: https://github.com/zenstruck/foundry/pull/754 should be merged first

fixes https://github.com/zenstruck/foundry/issues/749 (and maybe https://github.com/zenstruck/foundry/issues/752)

~I still need to add a non-regression test~ DONE :blush:

### CODE REVIEW

File: src/Persistence/PersistentObjectFactory.php [hunk 1]
```diff
@@ -34,11 +34,14 @@
...
 abstract class PersistentObjectFactory extends ObjectFactory
 {
-    private bool $persist;
+    private PersistMode $persist = PersistMode::PERSIST;
 
     /** @phpstan-var list<callable(T, Parameters, static):void> */
     private array $afterPersist = [];
 
+    /** @var list<callable(T):void> */
+    private array $tempAfterInstantiate = [];
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:43]: I don't like this solution... :shrug:

File: src/Persistence/PersistentObjectFactory.php [hunk 2]
```diff
@@ -277,20 +296,21 @@ protected function normalizeParameter(string $field, mixed $value): mixed
...
-                    $value->create([$inverseField => $object]);
-                    $pm->refresh($object);
-                    $oldObj = get($inversedObject, $inverseField);
-                    delete($inversedObject);
-                    if ($oldObj) {
-                        delete($oldObj); // @phpstan-ignore argument.templateType
-                    }
+                // we need to handle the circular dependency involved by inversed one-to-one relationship:
+                // a placeholder object is used, which will be replaced by the real object, after its instantiation
+                $inversedObject = $value->withoutPersistingButScheduleForInsert()
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:301]: we're creating the "child" object here, but it needs the object created by the current factory, and we're passing it an empty "placeholder". So we should not persist now, or it try to save the place holder and it will break. 

Otherwise, we should "schedule for insert" the "child" object, as well as all other objects that would be created by the factory `$value`. 

Hence this "persist" mode stuff

I tried the other way around, meaning creating a placeholder for the "child" object, but I didn't manage to make it work

**Review by kbond — APPROVED** [review]
