### PR TITLE
fix: add phpdoc to improve proxy factories autocompletion

### LINKED ISSUE #656: [2.0] No autocompletion for Proxy objects
With 2.0, I don't have autocompletion for Proxy methods (_real, etc ...) on proxied objects.

Using this Phpdoc : 
```
/**
 * @extends PersistentProxyObjectFactory<User>
 */
```

### PR DESCRIPTION
**Pull request by nikophil**
fixes https://github.com/zenstruck/foundry/issues/656

ping @ekvedaras (I'm closing your PR in favor of this one) / @simondaigre

### CODE REVIEW

File: src/Persistence/PersistentProxyObjectFactory.php [hunk 1]
```diff
@@ -42,23 +49,26 @@ abstract class PersistentProxyObjectFactory extends PersistentObjectFactory
     abstract public static function class(): string;
 
     /**
-     * @return T&Proxy<T>
+     * @return Proxy<T>
```
Comment (nikophil) [inline src/Persistence/PersistentProxyObjectFactory.php:52]: Curiously enough, PHPStorm does not understand `T&Proxy<T>` but it does understand `list<T&Proxy<T>>` :shrug:

**Comment by nikophil** [comment]
Hey @andersonamuller

I've added your modification inside this PR, because I think both are needed for a good autocompletion.
For now, I'll ignore the PHPStan failures, I'll ask on their repo if it is a legit failure or a false negative.

Here are my tests:
- `StandardFactory::createOne()` (no proxy): :white_check_mark: autocompletes methods from object
Capture d’écran du 2024-07-24 10-23-51

- `StandardFactory::new()->create()`: :heavy_exclamation_mark: autocompletes methods from object + methods from proxy where it should only autocomplete methods from object.
Capture d’écran du 2024-07-24 10-24-11

- `StandardFactory::new()->with()->create()`: :white_check_mark: autocompletes methods from object
Capture d’écran du 2024-07-24 10-25-00

- `ProxyFactory::createOne()`: :white_check_mark: autocompletes methods from object + methods from proxy. 
Capture d’écran du 2024-07-24 10-25-15

- `ProxyFactory::new()->create()`: :white_check_mark: autocompletes methods from object + methods from proxy. 
Capture d’écran du 2024-07-24 10-25-27


- `ProxyFactory::new()->with()->create()`: :bangbang: it should autocomplete proxy methods 
Capture d’écran du 2024-07-24 10-34-33

I'm struggling to make it perfect. 
I think the second case is ok-ish... It should not autocomplete proxy methods, but at least it autocompletes the object's methods.

For the last one, I could not make it display the proxy methods, even by adding an annotation `@method static<Proxy<T>> with()`  in `PersistentObjectFactory`.

Any help would be appreciated, otherwise I'll merge it as-is.

ping @kbond

**Review by kbond — APPROVED** [review]
