### PR TITLE
Instantiator improvements

### LINKED ISSUE #75: Remove attribute prefix when doing findOrCreate() ?
I'm not totally sure whether we're wrongly using this library or whether I have stumbled on a bug (I'm having this bug in so many places that I almost believe it's the first). That's why I decided to open an issue first, I'm happy to provide a PR to fix this issue.

---

In our code, some properties are not set by the constructor or by property accessible setters. E.g. a `User#subscribeTo($subscription)` method. However, I want to create fixtures with subscriptions. From what I understand, the `force:` attribute prefix is the way forward: `['force:subscription' => $subscription]`.

However, this does not work with `findOrCreate()`, as doctrine will try to use a field called `force:subscription` instead of the expected `subscription`. I'm often using `findOrCreate()` in my tests, as I want to avoid creating new test fixtures if a matching is already found.

The solution would be to strip attribute prefixes before passing them into `repository()->find($attributes)`: https://github.com/zenstruck/foundry/blob/ea8430f1ad295c88818e056ca565e5db2c528e0b/src/ModelFactory.php#L55-L59

### PR DESCRIPTION
**Pull request by kbond**
Fixes #75, Alternate to #77.

1. This deprecates the usage of the "force:" and "extra:" attribute prefixes. There were several problems (ref: #75 & https://github.com/zenstruck/foundry/pull/77#issuecomment-723344210).

    The new way of using is to define them on the `Instantiator` itself:

    ```php
    $factory->instantiateWith(
        (new Instantiator())->allowExtraAttributes(['extra1', 'extra2'])->alwaysForceProperties(['title', 'body'])
    );
    ```
2. This also deprecates using snake/kebab-case for attribute names for the same reasons as above.

### CODE REVIEW

**Comment by kbond** [comment]
Anyone know what's causing https://github.com/zenstruck/foundry/pull/81/checks?check_run_id=1374983511#step:9:22 ? Only with --prefer-lowest (maker-bundle 1.5.0). Ping @weaverryan

File: src/Instantiator.php [hunk 1]
```diff
@@ -79,20 +92,32 @@ public function withoutConstructor(): self
...
         return $this;
     }
 
     /**
      * Always force properties, never use setters (still uses constructor unless disabled).
+     *
+     * @param string ...$properties The properties you'd like the instantiator to "force set" (if empty, force set all)
      */
-    public function alwaysForceProperties(): self
+    public function alwaysForceProperties(string ...$properties): self
```
Comment (wouterj) [inline src/Instantiator.php:114]: Variadic arguments are difficult to manage in a BC way (it's no longer possible to add any optional argument after `$properties` in the future). I would recommend to go for a simple `array $properties = []` argument.

Comment (kbond) [reply src/Instantiator.php]: Good call.

File: src/Instantiator.php [hunk 2]
```diff
@@ -150,8 +151,11 @@ private static function accessibleProperty(object $object, string $name): \Refle
         $class = new \ReflectionClass($object);
 
         // try fetching first by exact name, if not found, try camel-case
-        if (!$property = self::reflectionProperty($class, $name)) {
-            $property = self::reflectionProperty($class, self::camel($name));
+        $property = self::reflectionProperty($class, $name);
+
+
+        if (!$property && $property = self::reflectionProperty($class, self::camel($name))) {
+            trigger_deprecation('zenstruck\foundry', '1.5.0', 'Using snake/kebab-case attributes is deprecated, use the same case as the object property instead.');
```
Comment (wouterj) [inline src/Instantiator.php:158]: This message is slightly incorrect, as it assumes the property name is camelCase. I would remove explicit case names, e.g: "Using a different case attribute is deprecated, [...]."

Comment (kbond) [reply src/Instantiator.php]: Changed to: "'Using a differently cased attribute is deprecated, use the same case as the object property instead.'"

**Review by weaverryan — APPROVED** [review]
seems reasonable :)
