### PR TITLE
Throw exception during auto-refresh if unsaved changes

### LINKED ISSUE #113: Auto-refresh proxy improvements
With [auto-refreshing](https://github.com/zenstruck/foundry#auto-refresh), there is a bit of a problem:

```php
$post = PostFactory::new(['title' => 'Original Title', 'body' => 'Original Body'])
    ->create()
    ->enableAutoRefresh()
;

$post->setTitle('New Title');
$post->setBody('New Body'); // !!! this causes the object to be refreshed, which means the "New Title" title was replaced by the database contents
$post->save();

$post->getBody(); // "New Body"
$post->getTitle(); // "Original Title" !! because the subsequent call to ->setBody() "auto-refreshed" the object
```

This is the reason auto-refreshing is disabled by default.

A great improvement would be to only refresh when it actually needs to be refreshed (it's row in the db changed).

If this could be fixed, I think we could enable auto-refreshing by default.

### PR DESCRIPTION
**Pull request by kbond**
When auto-refreshing a proxy, if there are unsaved changes detected, a helpful exception is thrown. Also, trigger deprecation if not specifically globally configured.

Closes #113.

### CODE REVIEW

File: src/Proxy.php [hunk 1]
```diff
@@ -108,10 +109,27 @@ public function isPersisted(): bool
      */
     public function object(): object
     {
-        if ($this->autoRefresh && $this->persisted) {
-            $this->refresh();
+        if (!$this->autoRefresh || !$this->persisted) {
+            return $this->object;
         }
 
+        // todo: what if object manager isn't entity manager?
```
Comment (weaverryan) [inline src/Proxy.php:116]: Do we support that in Foundry?

Comment (kbond) [reply src/Proxy.php:116]: Technically, yes but I've never tested with or even used an object manager other than the orm.

Comment (kbond) [reply src/Proxy.php:116]: I think I'll just check that it's an instance of `EntityManagerInterface` in the conditional below.

File: src/Proxy.php [hunk 2]
```diff
@@ -108,10 +109,24 @@ public function isPersisted(): bool
...
 
+        $om = $this->objectManager();
+
+        // only check for changes if the object is managed in the current om
+        if ($om instanceof EntityManagerInterface && $om->contains($this->object)) {
+            // cannot use UOW::recomputeSingleEntityChangeSet() here as it wrongly computes embedded objects as changed
+            $om->getUnitOfWork()->computeChangeSet($om->getClassMetadata($this->class), $this->object);
+
+            if (!empty($om->getUnitOfWork()->getEntityChangeSet($this->object))) {
+                throw new \RuntimeException(\sprintf('Cannot auto refresh "%s" as there are unsaved changes. Be sure to call ->save() or disable auto refreshing (see https://github.com/zenstruck/foundry#auto-refresh for details).', $this->class));
```
Comment (kbond) [inline src/Proxy.php:124]: How's this message?

File: README.md [hunk 3]
```diff
@@ -1580,7 +1579,7 @@ imports:
 zenstruck_foundry:
 
     # Whether to auto-refresh proxies by default (https://github.com/zenstruck/foundry#auto-refresh)
-    auto_refresh_proxies: false
+    auto_refresh_proxies: null # (defaults to false but will default to true in 2.0)
```
Comment (kbond) [inline README.md:1582]: How else should we document that this "needs" to be configured?

File: src/Configuration.php [hunk 4]
```diff
@@ -62,6 +62,12 @@ public function instantiator(): callable
 
     public function defaultProxyAutoRefresh(): bool
     {
+        if (null === $this->defaultProxyAutoRefresh) {
+            trigger_deprecation('zenstruck\foundry', '1.9', 'Not explicitly configuring default proxy auto-refresh ("zenstruck_foundry.auto_refresh_proxies" in config or TestState::enableDefaultProxyAutoRefresh()/disableDefaultProxyAutoRefresh()) is deprecated. It will default to true in 2.0.');
```
Comment (kbond) [inline src/Configuration.php:66]: How's this deprecation message?

File: README.md (hunk 3 above)
Comment (wouterj) [reply README.md:1582]: I would just say `auto_refresh_proxies: true`. The rest is implementation detail to me, and the code/deprecation message do a good enough job to help the user

File: src/Configuration.php (hunk 4 above)
Comment (wouterj) [reply src/Configuration.php:66]: What about:

Not explicitly configuring default proxy auto-refresh is deprecated and will default to true in 2.0. Use "zenstruck_foundry.auto_refresh_proxies" in the bundle config or TestState::enableDefaultProxyAutoRefresh()/disableDefaultProxyAutoRefresh().
