### PR TITLE
refactor: fix proxy system and introduce psalm extension

### LINKED ISSUE #701: Psalm errors with Attributes phpstan-type declaration
Hi !

I should have opened this issue a month ago (sorry about that) since I commented [here](https://github.com/zenstruck/foundry/issues/623#issuecomment-2342855336)  thinking it was related.

As mentionned in the linked comment, since `2.0.8` I started getting these kind of Psalm errors: 
```
InvalidArgument - src/DataFixtures/AppFixtures.php:128:70 - Argument 1 of App\Foundry\Factory\Node\EndConversationNodeFactory::createOne expects Zenstruck\Foundry\Persistence\Attributes, but array{position: App\Entity\Position, script: App\Entity\Script} provided (see https://psalm.dev/004)
```
From what I understand: Psalm doesn't seem to appreciate the fact that I pass an array instead of an instance of a non existing class Attributes to my factories like this:
```
EndConversationNodeFactory::createOne([
    'script' => $script,
]);
```

After some investigations it seems that these "errors" have been introduced by this [commit](https://github.com/zenstruck/foundry/commit/65c1cc2f6dc034435e325e7913bee41313f1b6a0)

and particularly by these added lines in the PersistentProxyObjectFactory 
image

if I remove `@method ` annotations, everything gets back to normal on my end, I'm trying to understand what's happening and my best guess is that  @method annotations should not use phpstan aliases like Attributes. 

Hope I was clear enough. If you need me to provide more information, just ask, I'd be happy to do so.

### PR DESCRIPTION
**Pull request by nikophil**
fixes https://github.com/zenstruck/foundry/issues/701 https://github.com/zenstruck/foundry/issues/696

I've decided to completely remove all methods in `PersistenceProxyObjectFactory`, so we do not override `@final` methods anymore. We still need to figure out a solution for `PersistenceObjectFactory::create()`, I'll do this in a further PR.

Psalm does not understand the following:
```php
/**
 * @extends PersistentProxyObjectFactory<User>
 */
class UserFactory extends PersistentProxyObjectFactory{}

/**
 * @template T of object
 * @extends PersistentObjectFactory<T&Proxy<T>>
 */
abstract class PersistentProxyObjectFactory extends PersistentObjectFactory{}

/**
 * @template T of object
 */
abstract class PersistentObjectFactory{}
```
it always consider the template to be `User` and not `User&Proxy<User>`. I think because we're breaking covariance (`T&Proxy<T>` is wider than `T`)

I've finally decided to introduce a psalm extension, we will be able to fix nearly every typing problem in here.

### CODE REVIEW

**Review by kbond — APPROVED** [review]
Looks good! I'm unfamiliar with psalm plugins, will this be auto-registered in projects using foundry and psalm?

**Comment by nikophil** [comment]
>  I'm unfamiliar with psalm plugins, will this be auto-registered in projects using foundry and psalm?

yes, thanks to [the change in composer.json](https://github.com/zenstruck/foundry/blob/cff5ae531b5fac15b6e7ec79052a25c46d129b02/composer.json#L74-L76)

**Review by deluxetom — APPROVED** [review]
Great solution, thank you!

File: src/Factory.php [hunk 1]
```diff
@@ -25,17 +25,18 @@
  */
 abstract class Factory
 {
-    /** @var Attributes[] */
+    /** @phpstan-var Attributes[] */
```
Comment (nikophil) [inline src/Factory.php:28]: everytime we use phpstan pseudo types, we should use `@phpstan-` annotations because Psalm seems to not understand it

and moreover, see this comment from stof [here](https://github.com/symfony/symfony/pull/50687#discussion_r1281529038), I think it is relevant

I'll make another PR where I fix all of the related docblocks

File: src/ObjectFactory.php [hunk 2]
```diff
@@ -58,6 +56,7 @@ public function create(callable|array $attributes = []): object
 
         $parameters = $this->normalizeParameters($parameters);
         $instantiator = $this->instantiator ?? Configuration::instance()->instantiator;
+        /** @var T $object */
```
Comment (nikophil) [inline src/ObjectFactory.php:59]: it seems like PHPStorm does not only interprets methods signature (like PHPStan would do) but it events guesses stuff from the methods' body. I had really hard times to find but it basically fixes 90% of auto-complete problems :tada:

File: src/Persistence/PersistentObjectFactory.php [hunk 3]
```diff
@@ -140,42 +126,40 @@ public static function random(array $criteria = []): object
...
-     * @final
-     *
      * @return T
      *
      * @throws \RuntimeException If no objects exist
      */
     public static function first(string $sortBy = 'id'): object
     {
-        return static::repository()->firstOrFail($sortBy);
+        /** @var T $object */
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:135]: same, this is here to help auto-complete

**Review by kbond — APPROVED** [review]
