### PR TITLE
fix(2.x): add back second parameter for after persist callbacks

### LINKED ISSUE #628: [2.x] ArgumentCountError thrown when passing $attributes array to closure in event
| Q | A
| --- | ---
| Symfony Version | 6.4.8
| Foundry Version | 2.0.1
| PHP Version | 8.3.8
| PHPUnit Version | 9.6.19

I've been upgrading my project to use Foundry v2.0. Everything has gone relatively smoothly except updating an event in one of my factory classes. I suspect the problem is on my end and not a bug, but I'm not sure what the problem is.

I'm using Foundry's default bundle configuration.

In a test I create an object as follows:

```php
$object = SomeEntityFactory::createOne([
    // standard entity properties

    // extra property
    'account' => [
        'name' => 'Account name',
        'uid' => 'UID',
    ],
]);
```

In 1.x, I did this:
```php
final class SomeEntityFactory extends ModelFactory
{
    // ...

    protected function initialize(): self
    {
        return $this
            ->instantiateWith((new Instantiator())->allowExtraAttributes(['account']))
            ->afterPersist(function (SomeEntity $object, array $attributes) {
                // do some stuff with $attributes['account']
            });
    }

    // ...
}
```

And for 2.x, I currently have this:
```php
final class SomeEntityFactory extends PersistentProxyObjectFactory
{
    // ...

    protected function initialize(): static
    {
        return $this
            ->instantiateWith(Instantiator::withConstructor()->allowExtra('account'))
            ->afterPersist(function (SomeEntity $object, array $attributes) {
                // do some stuff with $attributes['account']
            });
    }

    // ...
}
```

The latter causes an error in 2.x:
> ArgumentCountError : Too few arguments to function App\Tests\Factory\SomeEntity\SomeEntityFactory::App\Tests\Factory\SomeEntity\{closure}(), 1 passed in /path-to-project/vendor/zenstruck/foundry/src/Persistence/PersistentObjectFactory.php on line 230 and exactly 2 expected

PHPStan gives the following error:

> phpstan: Parameter # 1 $callback of method Zenstruck\Foundry\Persistence\PersistentObjectFactory<App\Entity\SomeEntity&Zenstruck\Foundry\Persistence\Proxy<App\Entity\SomeEntityt>>::afterPersist() expects callable(App\Entity\SomeEntity&Zenstruck\Foundry\Persistence\Proxy<App\Entity\SomeEntity>): void, Closure(App\Entity\SomeEntity, array): void given

> Parameter # 2 $attributes of passed callable is required but accepting callable does not have that parameter. It will be called without it.

I've gone over the documentation and upgrade guide to see what I might be doing wrong. I've attempted to debug the issue and that's only muddied things further.

I feel like I'm missing something obvious. What would be the correct way to achieve the above in 2.x?

Thank you!

### PR DESCRIPTION
**Pull request by nikophil**
fixes https://github.com/zenstruck/foundry/issues/628

### CODE REVIEW

File: src/Persistence/PersistentObjectFactory.php [hunk 1]
```diff
@@ -226,11 +226,13 @@ final public function create(callable|array $attributes = []): object
 
         $this->tempAfterPersist = [];
 
-        foreach ($this->afterPersist as $callback) {
-            $callback($object);
-        }
-
         if ($this->afterPersist) {
+            $attributes = $this->normalizeAttributes($attributes);
```
Comment (nikophil) [inline src/Persistence/PersistentObjectFactory.php:230]: not a huge fan of this:
- this is already done in `parent::create()`
- we won't pass attributes added in `beforeInstantiate` callbacks

any thought @kbond ?

File: docs/index.rst [hunk 2]
```diff
@@ -562,14 +562,6 @@ they were added.
             // $object is the instantiated object
             // $attributes contains the attributes used to instantiate the object and any extras
         })
-        ->afterPersist(function(Proxy $proxy, array $attributes) {
```
Comment (nikophil) [inline docs/index.rst:565]: we're not doing this anymore... This is a BC break between 1.x and 2.x :shrug:

File: src/Persistence/PersistentObjectFactory.php (hunk 1 above)
Comment (kbond) [reply src/Persistence/PersistentObjectFactory.php:230]: Hmm, I agree, this doesn't feel great. I guess I totally missed this part when working on 2.0...
