### PR TITLE
fix: handle proxies when refreshing entity in `Proxy::getState()`

### LINKED ISSUE #649: Global state relationships and flush_after
Hello,

I recently migrated to version 2.

I used to use `Factory::flushAfter` in my functional tests.

Using DAMA + global stories, when I create a object in a story (not global this one) using a relationship created in a global story I got a `A new entity was found through the relationship` error only if story is load with a `flush_after`.
I use `flush_after` because in my case, two entities has to created in the same transaction.

My config file : 
```php
<?php

declare(strict_types = 1);

use ...;

return static function (ZenstruckFoundryConfig $config, ContainerConfigurator $container): void {
    $config->faker()->locale('fr_FR');
    $config->globalState([
        GlobalState\ActivityStory::class,
		...,
        GlobalState\BusinessProviderStory::class,
        GlobalState\BusinessProviderOfferStory::class,
    ]);
    $config->orm(['auto_persist' => true, 'reset' => ['connections' => ['default'], 'entity_managers' => ['default'], 'mode' => 'migrate']]);
};
```

My call in test : `flush_after(static fn () => CreditNoteStory::load());`

If I update my business logic (ignoring error on missing linked entity in the same transaction), and remove the `flush_after` call, I haven't any error

Thank you for your help

### PR DESCRIPTION
**Pull request by nikophil**
fixes #649

### CODE REVIEW

File: src/Story.php [hunk 1]
```diff
@@ -132,7 +134,12 @@ final protected function getState(string $name): mixed
         }
 
         try {
-            return Configuration::instance()->persistence()->refresh($this->state[$name], force: true); // @phpstan-ignore argument.templateType
+            $isProxy = $this->state[$name] instanceof Proxy;
+
+            $unwrappedObject = ProxyGenerator::unwrap($this->state[$name]);
+            Configuration::instance()->persistence()->refresh($unwrappedObject, force: true); // @phpstan-ignore argument.templateType
+
+            return $isProxy ? ProxyGenerator::wrap($unwrappedObject) : $unwrappedObject; // @phpstan-ignore argument.templateType
```
Comment (nikophil) [inline src/Story.php:142]: I did not find anything simpler/cleaner that passes the test :shrug:

**Review by kbond — APPROVED** [review]
