### PR TITLE
fix: handle derived entities in autorefresh mechanism

### LINKED ISSUE #1056: Refresh fails for native proxy of entity with derived identity
The refresh of the `\Zenstruck\Foundry\Persistence\PersistenceManager` fails for an [derived entity](https://www.doctrine-project.org/projects/doctrine-orm/en/3.6/tutorials/composite-primary-keys.html#use-case-2-simple-derived-identity) with there error

```
Doctrine\ORM\ORMInvalidArgumentException: Binding entities to query parameters only allowed for entities that have an identifier.
Class "App\Entity\OwningSide" does not have an identifier.
``` 
thrown by the Doctrine-EntityManager

We have a setup like 

```php
#[ORM\Entity]
#[ORM\Table('inversed_one_to_one_with_owning_entity_as_id_owning_side')]
class OwningSide
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer', unique: true)]
    public ?int $id = null;

    #[ORM\OneToOne(targetEntity: InverseSide::class, mappedBy: 'owningSide')]
    public ?InverseSide $inverseSide = null;
}
```

```php
#[ORM\Entity]
#[ORM\Table('one_to_one_with_owning_entity_as_id_inverse_side')]
class InverseSide
{
    #[ORM\Column(type: Types::STRING)]
    private string $status = 'created';

    public function __construct(
        #[ORM\Id]
        #[ORM\OneToOne(targetEntity: OwningSide::class, inversedBy: 'inverseSide')]
        #[ORM\JoinColumn(name: 'owning_side_id', referencedColumnName: 'id')]
        private OwningSide $owningSide,
    ) {
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function getOwningSide(): OwningSide
    {
        return $this->owningSide;
    }

    public function setOwningSide(OwningSide $owningSide): void
    {
        $this->owningSide = $owningSide;
        $owningSide->inverseSide = $this;
    }
}
```

And a test case

```php
class ReproducerTest extends KernelTestCase
{
    use Factories;

    protected static function getKernelClass(): string
    {
        return \App\Kernel::class;
    }

    protected function setUp(): void
    {
        self::bootKernel();

        $entityManager = self::getContainer()->get('doctrine.orm.default_entity_manager');

        $schemaTool = new \Doctrine\ORM\Tools\SchemaTool($entityManager);
        $metadata = $entityManager->getMetadataFactory()->getAllMetadata();
        $schemaTool->dropDatabase();
        $schemaTool->updateSchema($metadata);
    }

    #[Test]
    public function one_to_one_with_owning_entity_as_id(): void
    {
        $this->expectNotToPerformAssertions();

        $owningSideFactory = persistent_factory(OwningSide::class)->withAutorefresh();
        $inverseSideFactory = persistent_factory(InverseSide::class)->withAutorefresh();

        $inverseSide = $inverseSideFactory->create(['owningSide' => $owningSideFactory]);

        $owningSideFactory::assert()->count(1);
        $inverseSideFactory::assert()->count(1);

        // we reset services here to have fresh entitymanager etc. i guess? Without this, refresh wont be triggered
        self::getContainer()->get(ServicesResetterInterface::class)->reset();

        $inverseSide->getStatus();
    }
}
```

In real life setup we use `$this->transport('async')->processOrFail(number: 1);` where the services are reset for the symfony messenger i assume. Without this the refresh wont be triggered

A reproducer can be found here https://github.com/tandev/zenstruck-foundry-derived-entity-proxy-issue-reproducer

### PR DESCRIPTION
**Pull request by nikophil**
fixes https://github.com/zenstruck/foundry/issues/1056

### CODE REVIEW

File: tests/Integration/ResetDatabase/ResetDatabaseTest.php [hunk 1]
```diff
@@ -54,6 +56,20 @@ public function it_generates_valid_schema(): void
             self::assertSame(2, $exit, \sprintf('Schema is not valid: %s', $commandOutput = $output->fetch()));
             self::assertStringContainsString('1 schema diff(s) detected', $commandOutput);
             self::assertStringContainsString('DROP TABLE doctrine_migration_versions', $commandOutput);
+        } elseif(ResetDatabaseTestKernel::usesSqlite()) {
+            // Don't know why sqlite always generate those requests with the derived entity ¯\_(ツ)_/¯
```
Comment (nikophil) [inline tests/Integration/ResetDatabase/ResetDatabaseTest.php:60]: this is reallly strange, and I've not found any info on internet, but I don't want to invest efforts here 🤷

**Comment by nikophil** [comment]
ping @tandev would you mind to test this fix, please?
