### PR TITLE
fix: do not flush global state twice when dama is not enabled

### LINKED ISSUE #487: fix CI
https://github.com/zenstruck/foundry/actions/runs/5762507081

### PR DESCRIPTION
**Pull request by nikophil**
fixes #487

not sure why this happened now (maybe because of the new exception in doctrine/orm) but without dama, the first test using `ResetDatabase` was flushing twice the global state, hence the error

### CODE REVIEW

File: src/Test/DatabaseResetter.php [hunk 1]
```diff
@@ -47,7 +47,7 @@ public static function resetDatabase(KernelInterface $kernel): void
 
         $databaseResetter->resetDatabase();
 
-        self::bootFoundry($kernel);
+        self::bootFoundry($kernel, flushGlobalState: $damaIsEnabled);
```
Comment (nikophil) [inline src/Test/DatabaseResetter.php:50]: we cannot directly use `self::isDAMADoctrineTestBundleEnabled()` because it checks if `StaticDriver::isKeepStaticConnections()` and at this point [it is disabled](https://github.com/zenstruck/foundry/blob/1.x/src/Test/ResetDatabase.php#L40) even if dama is used

**Review by kbond — APPROVED** [review]
Awesome, thanks for figuring this out!
