### PR TITLE
fix: fix deprecation message for Factories trait

### LINKED ISSUE #805: "In order to use Foundry, you must use the trait KernelTestCase" wrong ? (2.4)
Not sure where this comes from (i'll look tonight), and sorry if it has been fixed already -- or if this is on us.

But there is probably something amiss with the "current class" detection here

> 862x: Since zenstruck/foundry 2.4: In order to use Foundry, you must use the trait "Symfony\Bundle\FrameworkBundle\Test\KernelTestCase" in your "App\Tests\Integration\Repository\DossierRepositoryTest" tests. This will throw an exception in 3.0.
    862x in DossierRepositoryTest::setUp from App\Tests\Integration\Repository

The repository in question does extends KernelTestCase 🤷 

```php

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

// ...

/**
 * @covers \App\Repository\DossierRepository
 */
class DossierRepositoryTest extends KernelTestCase
{
```

### PR DESCRIPTION
**Pull request by nikophil**
fixes #805

### CODE REVIEW

File: tests/Integration/ForceFactoriesTraitUsage/KernelTestCaseWithoutFactoriesTraitTestCase.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ public function not_using_foundry_should_not_throw_even_when_container_is_used()
     #[IgnoreDeprecations]
     public function using_foundry_without_trait_should_throw(): void
     {
-        $this->expectUserDeprecationMessageMatches('/In order to use Foundry, you must use the trait/');
+        $this->expectUserDeprecationMessageMatches('/In order to use Foundry correctly, you must use the trait/');
```
Comment (nikophil) [inline tests/Integration/ForceFactoriesTraitUsage/KernelTestCaseWithoutFactoriesTraitTestCase.php:47]: I don't manage to make this work with the name of the trait :shrug:

**Comment by smnandre** [comment]
Ho well.. i answered a deleted comment ^^

**Comment by smnandre** [comment]
> 
  862x: Since zenstruck/foundry 2.4: In order to use Foundry correctly, you must use the trait "Zenstruck\Foundry\Test\Factories" in your "App\Tests\Integration\Repository\DossierRepositoryTest" tests. This will throw an exception in 3.0.
    862x in DossierRepositoryTest::setUp from App\Tests\Integration\Repository


Perfect!  👏  Thanks

**Comment by nikophil** [comment]
> Ho well.. i answered a deleted comment 

yeah I finally found out how to do this (with 4 `\`) :grin:
