### PR TITLE
fix: autorefresh should work after kernel shutdown

### LINKED ISSUE #1009: Objects not refreshing
Hello,

I recently upgraded to Foundry 2. According to the documentation, Foundry auto refreshes the objects when using php 8.4, but for some reason this is not working for me.

I have php 8.4.8, my factories extend from PersistenObjectFactory and my config file looks like this:

```yml
when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
        enable_auto_refresh_with_lazy_objects: true
        instantiator:
            use_constructor:  true
        orm:
            auto_persist:         true
            reset:
                connections: [default]
                entity_managers: [default]
                mode: schema

when@test: *dev
```

But in order to refresh my objects I have constantly call: $obj = ObjectFactory::repository()->last()

Here's an example of one of my tests:

```php
//Arrange
        $sequenceValue = 10;

        SequenceAuthorizationFactory::createOne([
            'sequenceType' => $invoiceType,
            'fromSequence' => 1,
            'toSequence'   => $sequenceValue + 50,
            'validFrom'    => new \DateTime('-1 day'),
            'validUntil'   => new \DateTime('+1 year'),
        ]);

        $sequence = SequenceFactory::createOne([
            'invoiceType'  => $invoiceType,
            'nextSequence' => $sequenceValue,
        ]);

        $invoice = InvoiceFactory::new([
            'invoiceType' => $invoiceType,
            'ncfDate'     => new \DateTime('2024-01-01 00:00:00'),
        ])
            ->withItems()
            ->withCompany()
            ->withContact()
            ->create();

        //Act
        $client = $this->createAuthenticatedClient();
        $client->xmlHttpRequest('POST', sprintf('/v1/es/invoices/%s/ncf', $invoice->getId()));

        $response = $client->getResponse();
        $responseData = json_decode($response->getContent(), true);

        $this->assertIsArray($responseData);
        $this->assertArrayHasKey('success', $responseData);

        // Unless I do this, the objects wont refresh
        $invoice = InvoiceFactory::repository()->last();
        $sequence = SequenceFactory::repository()->last();
```

and here's one of the factories:

```php
<?php

namespace SQManagement\Factory\Invoice;

use SQManagement\Entity\Invoice\Invoice;
use SQManagement\Entity\Invoice\SequenceAuthorization;
use Zenstruck\Foundry\Persistence\PersistentObjectFactory;

/**
 * @extends PersistentObjectFactory<SequenceAuthorization>
 */
final class SequenceAuthorizationFactory extends PersistentObjectFactory
{
    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#factories-as-services
     *
     * @todo inject services if required
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#model-factories
     *
     * @todo add your default values here
     */
    #[\Override]
    protected function defaults(): array
    {
        return [
            'fromSequence' => 1,
            'sequenceType' => self::faker()->randomElement([Invoice::GOV_INVOICE, Invoice::FISCAL_INVOICE, Invoice::CREDIT_NOTE, Invoice::SPECIAL_INVOICE]),
            'toSequence'   => 100,
            'validFrom'    => self::faker()->dateTimeThisMonth(),
            'validUntil'   => self::faker()->dateTimeBetween('+12 months', '+18 months'),
        ];
    }

    /**
     * @see https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#initialization
     */
    #[\Override]
    protected function initialize(): static
    {
        return $this
            // ->afterInstantiate(function(SequenceAuthorization $sequenceAuthorization): void {})
        ;
    }

    #[\Override]
    public static function class(): string
    {
        return SequenceAuthorization::class;
    }

    public function withSequenceType(string $type): self
    {
        return $this->with(['sequenceType' => $type]);
    }
}

```

Maybe there's something I'm not doing right?

Thanks

### PR DESCRIPTION
**Pull request by nikophil**
fixes #1009

### CODE REVIEW

File: src/Configuration.php [hunk 1]
```diff
@@ -130,7 +130,6 @@ public static function isBooted(): bool
     /** @param \Closure():self|self $configuration */
     public static function boot(\Closure|self $configuration): void
     {
-        PersistedObjectsTracker::reset();
```
Comment (nikophil) [inline src/Configuration.php:133]: culprit was here

**Comment by Kocal** [comment]
Hey!

I'm sorry for posting here, but it looks like this releases broke the Symfony UX tests-suite (https://github.com/symfony/ux/actions/runs/18675203003/job/53243634658?pr=3145), the test https://github.com/symfony/ux/blob/cd4dbe384bb4338a6ff9f384fdc6df7543e53db5/src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php#L46-L73 is not passing anymore: 
```
1) Symfony\UX\LiveComponent\Tests\Functional\EventListener\LiveComponentSubscriberTest::testCanRenderComponentAsHtml
Error: Typed static property Zenstruck\Foundry\Persistence\Proxy\PersistedObjectsTracker::$buffer must not be accessed before initialization

/home/runner/work/ux/ux/src/LiveComponent/vendor/zenstruck/foundry/src/Persistence/Proxy/PersistedObjectsTracker.php:53
/home/runner/work/ux/ux/src/LiveComponent/vendor/zenstruck/foundry/src/Persistence/PersistenceManager.php:89
/home/runner/work/ux/ux/src/LiveComponent/vendor/zenstruck/foundry/src/Persistence/PersistentObjectFactory.php:266
/home/runner/work/ux/ux/src/LiveComponent/vendor/zenstruck/foundry/src/Persistence/functions.php:89
/home/runner/work/ux/ux/src/LiveComponent/tests/Functional/EventListener/LiveComponentSubscriberTest.php:49
```

Do you know what can happens?
Thanks!

**Comment by nikophil** [comment]
hi @Kocal 

I won't be able to fix this today :grimacing: 

Please add a conflict on this version in you repo, I'll fix this tomorrow

File: src/Configuration.php (hunk 1 above)
Comment (maelanleborgne) [reply src/Configuration.php:133]: Hello !
 Looks like this change has side effect : 

```php
class FooTest extends WebTestCase
{
    use Factories;

    public function testFoo(): void
    {
        FooFactory::create();
    }
}
```

gives us

```
Error: Typed static property Zenstruck\Foundry\Persistence\Proxy\PersistedObjectsTracker::$buffer must not be accessed before initialization
/var/www/project/vendor/zenstruck/foundry/src/Persistence/Proxy/PersistedObjectsTracker.php:53
/var/www/project/vendor/zenstruck/foundry/src/Persistence/PersistenceManager.php:89
/var/www/project/vendor/zenstruck/foundry/src/Persistence/PersistentObjectFactory.php:266
/var/www/project/tests/Functional/FooTest.php:7
```


Is there anything special to do to initialize foundry with this new version ?

**Comment by Kocal** [comment]
No problem, at least you know.
Thanks! :)
