### PR TITLE
fix: enable compatibility with symfony 7.3 + PHP 8.4

### LINKED ISSUE #890: Symfony 7.3 error: Proxy contains 13 abstract methods (e.g. Zenstruck\Foundry\Persistence\Proxy::_enableAutoRefresh)
When I upgrade my project to Symfony 7.3 beta1, I get this error:                             

                                                                                                                                                                                                                                                                                           
  Error: Class AppEntitySacroProxy contains 13 abstract methods and must therefore be declared abstract or implement the remaining methods (Zenstruck\Foundry\Persistence\Proxy::_enableAutoRefresh, Zenstruck\Foundry\Persistence\Proxy::_disableAutoRefresh, Zenstruck\Foundry\Persistence\Proxy::_withoutAutoRefres  
  h, ...)                                                                                                                                                                                                                                                                                                               
                

It happens even when generating a new factory.

### PR DESCRIPTION
**Pull request by nikophil**
fixes https://github.com/zenstruck/foundry/issues/890

Here is a fix when using Symfony 7.3 AND PHP 8.4

since https://github.com/symfony/symfony/pull/59890 there was some changes in var-exporter, to support new php proxy system.

and because we're doing weird things, which deals with extra internal stuff with proxy system, things was failing :shrug: 

I think this is a very short term fix, since it won't be possible to rely on Symfony's `ProxyHelper` for Foundry's proxyh system. We'd need to find another way to do this

### CODE REVIEW

File: src/Persistence/ProxyGenerator.php [hunk 1]
```diff
@@ -114,12 +114,23 @@ private static function generateClassFor(object $object): string
             $proxyCode,
             [
                 'implements \Symfony\Component\VarExporter\LazyObjectInterface' => \sprintf('implements \%s, \Symfony\Component\VarExporter\LazyObjectInterface', Proxy::class),
+                'use \Symfony\Component\VarExporter\Internal\LazyDecoratorTrait' => \sprintf("use \\%s;\n    use \\%s", IsProxy::class, LazyProxyTrait::class),
                 'use \Symfony\Component\VarExporter\LazyProxyTrait' => \sprintf("use \\%s;\n    use \\%s", IsProxy::class, LazyProxyTrait::class),
```
Comment (nikophil) [inline src/Persistence/ProxyGenerator.php:118]: `symfony/var-exporter` used to generate code like this:
```php
class ZenstruckFoundryTestsFixtureEntityAddressProxy extends \Zenstruck\Foundry\Tests\Fixture\Entity\Address implements \Zenstruck\Foundry\Persistence\Proxy, \Symfony\Component\VarExporter\LazyObjectInterface
{
    use \Symfony\Component\VarExporter\LazyProxyTrait;
```

and then, we were replacing ` use \Symfony\Component\VarExporter\LazyProxyTrait` by 
```php
use \Symfony\Component\VarExporter\LazyProxyTrait;
use IsProxy;
```

but now, with php 8.4 + sf 7.3 (and only for this "combo"), it generates:
```php
class ZenstruckFoundryTestsFixtureEntityAddressProxy extends \Zenstruck\Foundry\Tests\Fixture\Entity\Address implements \Zenstruck\Foundry\Persistence\Proxy, \Symfony\Component\VarExporter\LazyObjectInterface
{
    use \Symfony\Component\VarExporter\Internal\LazyDecoratorTrait;
```

so let's replace both occurrences

File: src/Persistence/ProxyGenerator.php [hunk 2]
```diff
@@ -114,12 +114,23 @@ private static function generateClassFor(object $object): string
...
-                'if (isset($this->lazyObjectState)) {' => "\$this->_autoRefresh();\n\n        if (isset(\$this->lazyObjectReal)) {",
                 '\func_get_args()' => '$this->unproxyArgs(\func_get_args())',
             ],
         );
 
+        /**
+         * Add `$this->_autoRefresh();` after every method declaration.
+         */
+        $proxyCode = preg_replace_callback(
+            '/^(\s*(?:public|protected|private)?\s*(?:static\s+|final\s+|abstract\s+)*function\s+(?!__)\w+\s*\([^\)]*\)\s*):?\s*\??[\w\\\\]*\s*\{\s*$/m',
```
Comment (nikophil) [inline src/Persistence/ProxyGenerator.php:127]: sorry for this complex stuff, but I asked AI to generate the regex :shrug:

File: src/Persistence/ProxyGenerator.php [hunk 3]
```diff
@@ -114,12 +114,23 @@ private static function generateClassFor(object $object): string
...
+            function ($matches) {
+                return rtrim($matches[0]) . "\n    \$this->_autoRefresh();";
+            },
+            $proxyCode
+        );
```
Comment (nikophil) [inline src/Persistence/ProxyGenerator.php:132]: I had to rework how we introduce the call to `_autoRefresh()` 

`symfony/var-exporter` used to generate code like this for any method:
```php
    public function getContact(): ?\Zenstruck\Foundry\Tests\Fixture\Entity\Contact
    {
        if (isset($this->lazyObjectReal)) {
            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->getContact(...$this->unproxyArgs(\func_get_args()));
        }

        return parent::getContact(...$this->unproxyArgs(\func_get_args()));
    }
```
so we were relying on the `if()` to introduce the call. But now, with php 8.4 + sf 7.3 (again, only for this combo), there is no more if, so I changed how it worked to use a regex which looks for any method declaration

File: tests/Unit/Persistence/ProxyGeneratorTest.php [hunk 4]
```diff
@@ -40,6 +46,37 @@ public static function classWithUnserializeMagicMethodProvider(): iterable
...
     }
+
+    /**
+     * @test
+     */
+    #[Test]
+    public function it_can_generate_proxy_for_class_with_self_return_type(): void
+    {
+        $proxyfiedObj = ProxyGenerator::wrap($obj = new ClassWithSelfReturnType());
+        self::assertSame($obj, $proxyfiedObj->returnsSelf()->_real()); // @phpstan-ignore method.notFound
```
Comment (nikophil) [inline tests/Unit/Persistence/ProxyGeneratorTest.php:57]: this is a change in sf 7.3: now methods which returns self/$this/static can now return a proxy

I think this is kinda nice, but I'm expecting some issues with subtle bugs poping because of this :shrug:

File: src/Persistence/ProxyGenerator.php [hunk 5]
```diff
@@ -114,12 +114,32 @@ private static function generateClassFor(object $object): string
...
+         * ):?\s*\??[\w\\\\]*                   # 7. Optional return type, can be nullable (starts with `?`), supports namespaced types (`\Foo\Bar`)
+         * \s*\{\s*$                            # 8. Opening brace `{` at the end of the line, with optional spaces before
+         */
+        $proxyCode = preg_replace_callback(
+            '/^(\s*(?:public|protected|private)?\s*function\s+(?!__)\w+\s*\([^\)]*\)\s*):?\s*\??[\w\\\\]*\s*\{\s*$/m',
+            function ($matches) {
+                return rtrim($matches[0]) . "\n    \$this->_autoRefresh();";
+            },
+            $proxyCode
+        );
```
Comment (nikophil) [inline src/Persistence/ProxyGenerator.php:141]: I had to rework how we introduce the call to `_autoRefresh()` 

`symfony/var-exporter` used to generate code like this for any method:
```php
    public function getContact(): ?\Zenstruck\Foundry\Tests\Fixture\Entity\Contact
    {
        if (isset($this->lazyObjectReal)) {
            return ($this->lazyObjectState->realInstance ??= ($this->lazyObjectState->initializer)())->getContact(...$this->unproxyArgs(\func_get_args()));
        }

        return parent::getContact(...$this->unproxyArgs(\func_get_args()));
    }
```
so we were relying on the `if()` to introduce the call. But now, with php 8.4 + sf 7.3 (again, only for this combo), there is no more if, so I changed how it worked to use a regex which looks for any method declaration

Sorry for the complex regex, but I asked the AI to help me here

**Review by kbond — APPROVED** [review]
